# Generated by Django 3.0.6 on 2020-07-20 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitedelivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cliente',
        ),
    ]
