# Generated by Django 3.0.8 on 2020-07-21 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitedelivery', '0002_remove_produto_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(blank=True, choices=[('TERESINA', 'TERESINA'), ('TIMOM', 'TIMOM')], max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, choices=[('PI', 'PIAUI'), ('MA', 'MARANHAO')], max_length=100, null=True, verbose_name='U F')),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='estado',
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('zona', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zona')),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bairro_cidade', to='sitedelivery.Cidade', verbose_name='Cidade')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_bairro', to='sitedelivery.Bairro', verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_cidade', to='sitedelivery.Cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='bairro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrega_bairro', to='sitedelivery.Bairro', verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrega_cidade', to='sitedelivery.Cidade', verbose_name='Cidade'),
        ),
    ]
