# Generated by Django 3.0.8 on 2020-07-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedelivery', '0003_auto_20200721_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='bairro',
            name='cobertura',
            field=models.CharField(blank=True, choices=[('S', 'SIM'), ('N', 'NAO')], max_length=1, null=True, verbose_name='Entregar neste Bairro?'),
        ),
    ]
