# Generated by Django 3.0.8 on 2020-07-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedelivery', '0004_bairro_cobertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bairro',
            name='zona',
            field=models.CharField(blank=True, choices=[('RC', 'REGIAO CENTRAL'), ('ZN', 'ZONA NORTE'), ('ZS', 'ZONA SUL'), ('ZL', 'ZONA LESTE'), ('ZD', 'ZONA SUDESTE')], max_length=2, null=True, verbose_name='Zona'),
        ),
    ]
