# Generated by Django 3.0.8 on 2020-07-23 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitedelivery', '0005_auto_20200721_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bairro',
            name='cidade',
            field=models.ForeignKey(default='TERESINA', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bairro_cidade', to='sitedelivery.Cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='cobertura',
            field=models.CharField(blank=True, choices=[('S', 'SIM'), ('N', 'NAO')], default='N', max_length=1, null=True, verbose_name='Entregar neste Bairro?'),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='zona',
            field=models.CharField(blank=True, choices=[('RC', 'REGIAO CENTRAL'), ('ZN', 'ZONA NORTE'), ('ZS', 'ZONA SUL'), ('ZL', 'ZONA LESTE'), ('ZD', 'ZONA SUDESTE')], default='ZD', max_length=2, null=True, verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='bebida',
            field=models.CharField(choices=[('ANTARCTICA', 'ANTARCTICA'), ('BADER', 'BADER'), ('BAVARIA', 'BAVARIA'), ('BOHEMIA', 'BOHEMIA'), ('BRAHMA', 'BRAHMA'), ('BUDWEISER', 'BUDWEISER'), ('CARACU', 'CARACU'), ('CORONA', 'CORONA'), ('CRYSTAL', 'CRYSTAL'), ('DEVASSA', 'DEVASSA'), ('EISENBAHN', 'EISENBAHN'), ('GLACIAL', 'GLACIAL'), ('GUARANA ANTARCTICA', 'GUARANA ANTARCTICA'), ('GUARANA FANTA', 'GUARANA FANTA'), ('GUARANA SCHIN', 'GUARANA SCHIN'), ('HEINEKEN', 'HEINEKEN'), ('ITAIPAVA', 'ITAIPAVA'), ('KAISER', 'KAISER'), ('PETRA', 'PETRA'), ('REFRI COCACOLA', 'REFRI COCA COLA'), ('REFRI FANTA LARANJA', 'REFRI FANTA LARANJA'), ('REFRI FANTA UVA', 'REFRI FANTA UVA'), ('SCHIN', 'SCHIN'), ('SKOL', 'SKOL'), ('STELLA', 'STELLA'), ('TERESOPOLIS', 'TERESOPOLIS'), ('TIJUCA', 'TIJUCA')], help_text='Selecione o produto', max_length=100, verbose_name='Bebida'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(choices=[('KS RETORNAVEL', 'KS RETORNAVEL'), ('LATA 350 ML', 'LATA 350 ML'), ('LATAO 550 ML', 'LATA 550 ML'), ('LATAO 473 ML', 'LATAO 473 ML'), ('LATINHA 269 ML', 'LATINHA 269 ML'), ('LITRAO 1000 ML', 'LITRAO 1000 ML'), ('LITRAO 990 ML', 'LITRAO 990 ML'), ('LITRO 600 ML', 'LITRO 600 ML'), ('LONG NECK 250 ML', 'LONG NECK 250 ML'), ('LONG NECK 275 ML', 'LONG NECK 275 ML'), ('LONG NECK 330 ML', 'LONG NECK 330 ML'), ('LONG NECK 350 ML', 'LONG NECK 350 ML'), ('LONG NECK 355 ML', 'LONG NECK 355 ML'), ('PERIGUETE 300 ML', 'PERIGUETE 300 ML'), ('PET 1 LTS', 'PET 1 LTS'), ('PET 1 LTS RETORNAVEL', 'PET 1 LTS RETORNAVEL'), ('PET 1.5 LTS', 'PET 1.5 LTS'), ('PET 1.5 LTS RETORNAVEL', 'PET 1.5 LTS RETORNAVEL'), ('PET 2 LITROS RETORNAVEL', 'PET 2  LTS RETORNAVEL'), ('PET 2 LTS', 'PET 2 LTS'), ('PET 2 LITROS', 'PET 2 LTS'), ('PET 2 LTS RETORNAVEL', 'PET 2 LTS RETORNAVEL')], help_text='Selecione a quantidade/tamanho', max_length=100, verbose_name='Tamanho'),
        ),
    ]
