# Generated by Django 3.0.8 on 2020-07-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedelivery', '0007_auto_20200724_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bairro',
            options={'verbose_name': '4 - Cadastro de Bairro', 'verbose_name_plural': '4 - Cadastro de Bairros'},
        ),
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name': '3 - Cadastro de Cidade', 'verbose_name_plural': '3 - Cadastro de Cidades'},
        ),
        migrations.AlterModelOptions(
            name='libera',
            options={'verbose_name': '2 - Liberação de Página', 'verbose_name_plural': '2 - Liberação de Páginas'},
        ),
        migrations.AlterField(
            model_name='libera',
            name='pagina',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Pagina '),
        ),
    ]
