# Generated by Django 3.0.8 on 2020-07-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedelivery', '0008_auto_20200724_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='bairro',
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='cidade',
            field=models.CharField(blank=True, choices=[('TERESINA', 'TERESINA'), ('TIMOM', 'TIMOM')], max_length=30, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='estado',
            field=models.CharField(blank=True, choices=[('PI', 'PIAUI'), ('MA', 'MARANHAO')], max_length=2, null=True, verbose_name='U F'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
    ]
