# Generated by Django 3.0.8 on 2020-07-27 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitedelivery', '0010_auto_20200724_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bairro',
            options={'verbose_name': '4  Cadastro de Bairro', 'verbose_name_plural': '4  Cadastro de Bairros'},
        ),
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name': '3  Cadastro de Cidade', 'verbose_name_plural': '3  Cadastro de Cidades'},
        ),
        migrations.AlterModelOptions(
            name='libera',
            options={'verbose_name': '2  Liberação de Página', 'verbose_name_plural': '2  Liberação de Páginas'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['bebida'], 'verbose_name': '1  Cadastro e manutenção de Produto', 'verbose_name_plural': '1  Cadastro e manutenção de Produtos'},
        ),
        migrations.AlterField(
            model_name='bairro',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bairro_cidade', to='sitedelivery.Cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='bebida',
            field=models.CharField(choices=[('ANTARCTICA', 'CERVEJA ANTARCTICA'), ('ANTARCTICA ORIGINAL', 'CERVEJA ANTARCTICA ORIGINAL'), ('ANTARCTICA SUB-ZERO', 'CERVEJA ANTARCTICA SUB-ZERO'), ('BADER', 'CERVEJA BADER'), ('BAVARIA', 'CERVEJA BAVARIA'), ('BOHEMIA', 'CERVEJA BOHEMIA'), ('BRAHMA', 'CERVEJA BRAHMA'), ('BRAHMA DUPLO MALTE', 'CERVEJA BRAHMA DUPLO MALTE'), ('BUDWEISER', 'CERVEJA BUDWEISER'), ('CARACU', 'CERVEJA CARACU'), ('CORONA', 'CERVEJA CORONA'), ('CRYSTAL', 'CERVEJA CRYSTAL'), ('DEVASSA', 'CERVEJA DEVASSA'), ('EISENBAHN', 'CERVEJA EISENBAHN'), ('GLACIAL', 'CERVEJA GLACIAL'), ('HEINEKEN', 'CERVEJA HEINEKEN'), ('ITAIPAVA', 'CERVEJA ITAIPAVA'), ('KAISER', 'CERVEJA KAISER'), ('PETRA', 'CERVEJA PETRA'), ('SCHIN', 'CERVEJA SCHIN'), ('SKOL', 'CERVEJA SKOL'), ('STELLA', 'CERVEJA STELLA'), ('TERESOPOLIS', 'CERVEJA TERESOPOLIS'), ('TIJUCA', 'CERVEJA TIJUCA'), ('GUARANA ANTARCTICA', 'GUARANA ANTARCTICA'), ('GUARANA FANTA', 'GUARANA FANTA'), ('GUARANA KUAT', 'GUARANA KUAT'), ('GUARANA SCHIN', 'GUARANA SCHIN'), ('COCACOLA', 'REFRIGERANTE COCA COLA'), ('FANTA LARANJA', 'REFRIGERANTE FANTA LARANJA'), ('FANTA UVA', 'REFRIGERANTE FANTA UVA')], help_text='Selecione o produto', max_length=100, verbose_name='Bebida'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='complemento',
            field=models.CharField(blank=True, choices=[('Cerveja Dortmunder Export', 'Cerveja Dortmunder Export'), ('Cerveja Dry Beer', 'Cerveja Dry Beer'), ('Cerveja Duplo Malte', 'Cerveja Duplo Malte'), ('Cerveja Heles', 'Cerveja Heles'), ('Cerveja Lager', 'Cerveja Lager'), ('Cerveja Pilsen', 'Cerveja Pilsen'), ('Cerveja Premium', 'Cerveja Premium'), ('Cerveja Puro Malte', 'Cerveja Puro Malte'), ('Guarana', 'Guarana'), ('Refrigerante', 'Refrigerante'), ('Refrigerante Cola', 'Refrigerante Cola')], help_text='Complemento de informações do produto', max_length=200, null=True, verbose_name='Descrição Complementar'),
        ),
    ]
