# Generated by Django 3.0.8 on 2020-07-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedelivery', '0011_auto_20200727_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='libera',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link da Pagina'),
        ),
        migrations.AlterField(
            model_name='libera',
            name='pagina',
            field=models.CharField(blank=True, choices=[('delivery', 'Delivery'), ('catalogo', 'Catalogo')], max_length=40, null=True, verbose_name='Pagina'),
        ),
    ]
