# Generated by Django 3.0.8 on 2020-08-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedelivery', '0012_auto_20200728_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bairro',
            options={'ordering': ['bairro'], 'verbose_name': '4  Cadastro de Bairro', 'verbose_name_plural': '4  Cadastro de Bairros'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['bebida', 'complemento'], 'verbose_name': '1  Cadastro e manutenção de Produto', 'verbose_name_plural': '1  Cadastro e manutenção de Produtos'},
        ),
        migrations.AddField(
            model_name='produto',
            name='classificacao',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18')], default='SIM', max_length=3, verbose_name='Classificaçao no site?'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='bebida',
            field=models.CharField(choices=[('CACHAÇA MAGUEIRA', 'CACHAÇA MAGUEIRA'), ('CACHAÇA MAGUEIRA OURO', 'CACHAÇA MAGUEIRA OURO'), ('CAJUINA NODESTINA', 'CAJUINA NODESTINA'), ('CARVAO', 'CARVAO'), ('ANTARCTICA', 'CERVEJA ANTARCTICA'), ('ANTARCTICA ORIGINAL', 'CERVEJA ANTARCTICA ORIGINAL'), ('ANTARCTICA SUB-ZERO', 'CERVEJA ANTARCTICA SUB-ZERO'), ('BADER', 'CERVEJA BADER'), ('BAVARIA', 'CERVEJA BAVARIA'), ('BOHEMIA', 'CERVEJA BOHEMIA'), ('BRAHMA', 'CERVEJA BRAHMA'), ('BRAHMA DUPLO MALTE', 'CERVEJA BRAHMA DUPLO MALTE'), ('BUDWEISER', 'CERVEJA BUDWEISER'), ('CARACU', 'CERVEJA CARACU'), ('CORONA', 'CERVEJA CORONA'), ('CRYSTAL', 'CERVEJA CRYSTAL'), ('DEVASSA', 'CERVEJA DEVASSA'), ('EISENBAHN', 'CERVEJA EISENBAHN'), ('GLACIAL', 'CERVEJA GLACIAL'), ('HEINEKEN', 'CERVEJA HEINEKEN'), ('ITAIPAVA', 'CERVEJA ITAIPAVA'), ('KAISER', 'CERVEJA KAISER'), ('PETRA', 'CERVEJA PETRA'), ('SCHIN', 'CERVEJA SCHIN'), ('SKOL', 'CERVEJA SKOL'), ('STELLA', 'CERVEJA STELLA'), ('TERESOPOLIS', 'CERVEJA TERESOPOLIS'), ('TIJUCA', 'CERVEJA TIJUCA'), ('GELO', 'GELO'), ('GUARANA ANTARCTICA', 'GUARANA ANTARCTICA'), ('GUARANA FANTA', 'GUARANA FANTA'), ('GUARANA KUAT', 'GUARANA KUAT'), ('GUARANA SCHIN', 'GUARANA SCHIN'), ('COCACOLA', 'REFRIGERANTE COCA COLA'), ('FANTA LARANJA', 'REFRIGERANTE FANTA LARANJA'), ('FANTA UVA', 'REFRIGERANTE FANTA UVA'), ('VINHO GAUCHO', 'VINHO GAUCHO'), ('VINHO PADRE CICERO', 'VINHO PADRE CICERO'), ('VINHO QUINTO DO MORGADO', 'VINHO QUINTO DO MORGADO'), ('VODKA SLOVA', 'VODKA SLOVA')], help_text='Selecione o produto', max_length=100, verbose_name='Bebida'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='complemento',
            field=models.CharField(blank=True, choices=[('Cachaça', 'Cachaça'), ('Cajuina', 'Cajuina'), ('Carvao Vegetal', 'Carvao Vegetal'), ('Cerveja Dortmunder Export', 'Cerveja Dortmunder Export'), ('Cerveja Dry Beer', 'Cerveja Dry Beer'), ('Cerveja Duplo Malte', 'Cerveja Duplo Malte'), ('Cerveja Heles', 'Cerveja Heles'), ('Cerveja Lager', 'Cerveja Lager'), ('Cerveja Pilsen', 'Cerveja Pilsen'), ('Cerveja Premium', 'Cerveja Premium'), ('Cerveja Puro Malte', 'Cerveja Puro Malte'), ('Gelo em cubos', 'Gelo em cubos'), ('Guarana', 'Guarana'), ('Refrigerante', 'Refrigerante'), ('Refrigerante Cola', 'Refrigerante Cola'), ('Vinho', 'Vinho'), ('Vodka', 'Vodka')], help_text='Complemento de informações do produto', max_length=200, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='site',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO')], default='SIM', help_text='Informe se o produto vai aparecer no site', max_length=3, verbose_name='Apresentar no site?'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(choices=[('GARRAFA 1 LT RETORNAVEL', 'GARRAFA 1 LT RETORNAVEL'), ('GARRAFA 400 ML', 'GARRAFA 400 ML'), ('GARRAFA 480 ML', 'GARRAFA 480 ML'), ('GARRAFA 490 ML', 'GARRAFA 490 ML'), ('GARRAFA 550 ML', 'GARRAFA 550 ML'), ('GARRAFA 750 ML', 'GARRAFA 750 ML'), ('GARRAFA 890 ML', 'GARRAFA 890 ML'), ('GARRAFA 960 ML', 'GARRAFA 960 ML'), ('GARRAFA 970 ML', 'GARRAFA 970 ML'), ('KS RETORNAVEL', 'KS RETORNAVEL'), ('LATA 350 ML', 'LATA 350 ML'), ('LATAO 550 ML', 'LATA 550 ML'), ('LATAO 473 ML', 'LATAO 473 ML'), ('LATINHA 269 ML', 'LATINHA 269 ML'), ('LITRAO 1000 ML', 'LITRAO 1000 ML'), ('LITRAO 990 ML', 'LITRAO 990 ML'), ('LITRO 600 ML', 'LITRO 600 ML'), ('LONG NECK 250 ML', 'LONG NECK 250 ML'), ('LONG NECK 275 ML', 'LONG NECK 275 ML'), ('LONG NECK 330 ML', 'LONG NECK 330 ML'), ('LONG NECK 350 ML', 'LONG NECK 350 ML'), ('LONG NECK 355 ML', 'LONG NECK 355 ML'), ('PERIGUETE 300 ML', 'PERIGUETE 300 ML'), ('PET 1 LTS', 'PET 1 LTS'), ('PET 1 LTS RETORNAVEL', 'PET 1 LTS RETORNAVEL'), ('PET 1.5 LTS', 'PET 1.5 LTS'), ('PET 1.5 LTS RETORNAVEL', 'PET 1.5 LTS RETORNAVEL'), ('PET 2 LITROS RETORNAVEL', 'PET 2  LTS RETORNAVEL'), ('PET 2 LTS', 'PET 2 LTS'), ('PET 2 LITROS', 'PET 2 LTS'), ('PET 2 LTS RETORNAVEL', 'PET 2 LTS RETORNAVEL')], help_text='Selecione a quantidade/tamanho', max_length=100, verbose_name='Tamanho'),
        ),
    ]
