# Generated by Django 3.0.8 on 2020-08-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedelivery', '0013_auto_20200811_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['classificacao', 'bebida', 'complemento'], 'verbose_name': '1  Cadastro e manutenção de Produto', 'verbose_name_plural': '1  Cadastro e manutenção de Produtos'},
        ),
        migrations.AlterField(
            model_name='produto',
            name='classificacao',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18')], max_length=3, verbose_name='Classificaçao no site?'),
        ),
    ]
